# Generated by Django 2.1.7 on 2019-04-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=200)),
                ('pergunta', models.ManyToManyField(to='perguntas.Pergunta')),
            ],
        ),
    ]
