# Generated by Django 2.1.7 on 2019-04-18 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='pergunta',
            new_name='perguntas',
        ),
    ]
