# Generated by Django 2.1.7 on 2019-04-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
        ('formularios', '0003_auto_20190417_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='perguntas',
        ),
        migrations.AddField(
            model_name='formulario',
            name='perguntas',
            field=models.ManyToManyField(to='perguntas.Pergunta'),
        ),
    ]
